version: '3'

services:
  otls:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RELIC_CURVE: ${RELIC_CURVE:-BLS12-446}  # Default to BLS12-446 if not set
    volumes:
      - ./:/opt/primus/otls
    ports:
      - "12345-12350:12345-12350"
    working_dir: /opt/primus/otls
    command: /bin/bash
    stdin_open: true
    tty: true 