version: '3'

services:
  otls:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/primus/otls
    ports:
      - "12345-12350:12345-12350"
    working_dir: /opt/primus/otls
    command: /bin/bash
    stdin_open: true
    tty: true 